using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using kaja.App_Code.Model;

namespace kaja
{
    public partial class Form2 : Form
    {
        kaja.App_Code.Model.Model2 _dbContext;
        public Form2()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            _dbContext = new kaja.App_Code.Model.Model2();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            _dbContext.DbCllientMaster.LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
    gridControl1.DataSource = _dbContext.DbCllientMaster.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void gridControl1_Click(object sender, EventArgs e)
        {
            Client_Master kli = new Client_Master();
            kli.Id = 1000;
            kli.Cl_Name = "klientetxo1000";
            

            //_dataContext.DBCAGE.Add(kaxa);
            //_dataContext.SaveChanges();

            //gridView1.AddNewRow(kaxa);

            _dbContext.DbCllientMaster.Add(kli);
            _dbContext.SaveChanges();

            //gridControl1.RefreshDataSource();
        }
    }
}
