using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using kaja.App_Code.Model;

namespace kaja
{
    public partial class Form1 : Form
    {
        kaja.App_Code.Model.Model1 _dbContext;
        public Form1()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            _dbContext = new kaja.App_Code.Model.Model1();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            _dbContext.DBCAGE.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                gridControl1.DataSource = _dbContext.DBCAGE.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void gridControl1_Click(object sender, EventArgs e)
        {
            ANDROID_CAGE kaxa = new ANDROID_CAGE();
            kaxa.IDCAGE = 100;
            kaxa.AREA = "a";
            kaxa.ESTANTE = "e";

            //_dataContext.DBCAGE.Add(kaxa);
            //_dataContext.SaveChanges();

            //gridView1.AddNewRow(kaxa);

            _dbContext.DBCAGE.Add(kaxa);
            _dbContext.SaveChanges();

            //gridControl1.RefreshDataSource();
        }
    }
}
